"""create lights table

Revision ID: 2b7fb9724ad0
Revises: 
Create Date: 2019-06-18 20:06:12.341475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b7fb9724ad0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('io_port', sa.Integer(), nullable=True),
    sa.Column('room', sa.String(length=64), nullable=True),
    sa.Column('controller', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lights')
    # ### end Alembic commands ###
